---
- name: Add Erlang repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian squeeze contrib' state=present

- name: Add Erlang repo key
  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc

- name: Update apt cache
  apt: update_cache=yes
 
- name: Install build-essential
  apt: pkg=build-essential
 
- name: Install Erlang
  apt: pkg=erlang

- name: Install Erlang doc
  apt: pkg=erlang-doc

- name: Install libsqlite3-dev (needed by sumo_db)
  apt: pkg=libsqlite3-dev
